name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install go-semantic-release
        run: |
          curl -sSfL https://raw.githubusercontent.com/go-semantic-release/semantic-release/master/install.sh | sh -s -- -b /usr/local/bin latest

      - name: Run go-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release
